import type { Question } from "@/lib/types";

export const questions: Question[] = [
  {
    id: "p1-morning",
    part: 1,
    topic: "Daily life",
    prompt: "What do you usually do in the morning?",
    prepSeconds: 0,
    answerSeconds: 45,
  },
  {
    id: "p1-hometown",
    part: 1,
    topic: "Hometown",
    prompt: "What do you like most about your hometown?",
    prepSeconds: 0,
    answerSeconds: 45,
  },
  {
    id: "p1-reading",
    part: 1,
    topic: "Reading",
    prompt: "Do you prefer reading printed books or digital books? Why?",
    prepSeconds: 0,
    answerSeconds: 45,
  },
  {
    id: "p1-technology",
    part: 1,
    topic: "Technology",
    prompt: "Which piece of technology do you use most often?",
    prepSeconds: 0,
    answerSeconds: 45,
  },
  {
    id: "p1-cooking",
    part: 1,
    topic: "Cooking",
    prompt: "How often do you cook for yourself?",
    prepSeconds: 0,
    answerSeconds: 45,
  },
  {
    id: "p1-weekends",
    part: 1,
    topic: "Weekends",
    prompt: "What does an ideal weekend look like for you?",
    prepSeconds: 0,
    answerSeconds: 45,
  },
  {
    id: "p1-photos",
    part: 1,
    topic: "Photography",
    prompt: "When do you usually take photos?",
    prepSeconds: 0,
    answerSeconds: 45,
  },
  {
    id: "p1-transport",
    part: 1,
    topic: "Transport",
    prompt: "How do you normally travel around your city?",
    prepSeconds: 0,
    answerSeconds: 45,
  },
  {
    id: "p2-skill",
    part: 2,
    topic: "A useful skill",
    prompt: "Describe a useful skill you learned outside school.",
    cuePoints: [
      "what the skill is",
      "when and how you learned it",
      "how you use it",
      "why it is useful to you",
    ],
    prepSeconds: 60,
    answerSeconds: 120,
  },
  {
    id: "p2-conversation",
    part: 2,
    topic: "A conversation",
    prompt: "Describe a conversation that changed the way you think.",
    cuePoints: [
      "who you spoke with",
      "where the conversation happened",
      "what you discussed",
      "why it influenced you",
    ],
    prepSeconds: 60,
    answerSeconds: 120,
  },
  {
    id: "p2-place",
    part: 2,
    topic: "A quiet place",
    prompt: "Describe a quiet place where you enjoy spending time.",
    cuePoints: [
      "where it is",
      "what it looks like",
      "what you do there",
      "how you feel in this place",
    ],
    prepSeconds: 60,
    answerSeconds: 120,
  },
  {
    id: "p2-advice",
    part: 2,
    topic: "Helpful advice",
    prompt: "Describe a piece of advice that was useful to you.",
    cuePoints: [
      "who gave you the advice",
      "what the advice was",
      "when you received it",
      "how it helped you",
    ],
    prepSeconds: 60,
    answerSeconds: 120,
  },
  {
    id: "p2-object",
    part: 2,
    topic: "A useful object",
    prompt: "Describe an object you use almost every day.",
    cuePoints: [
      "what the object is",
      "when you got it",
      "how you use it",
      "why it is important to you",
    ],
    prepSeconds: 60,
    answerSeconds: 120,
  },
  {
    id: "p2-event",
    part: 2,
    topic: "A small celebration",
    prompt: "Describe a small celebration that you enjoyed.",
    cuePoints: [
      "what you celebrated",
      "who was there",
      "what happened",
      "why you remember it",
    ],
    prepSeconds: 60,
    answerSeconds: 120,
  },
  {
    id: "p2-person",
    part: 2,
    topic: "An interesting person",
    prompt: "Describe someone whose way of thinking interests you.",
    cuePoints: [
      "who this person is",
      "how you know them",
      "what ideas they have",
      "why you find them interesting",
    ],
    prepSeconds: 60,
    answerSeconds: 120,
  },
  {
    id: "p3-learning",
    part: 3,
    topic: "Learning",
    prompt: "How has technology changed the way adults learn new skills?",
    prepSeconds: 10,
    answerSeconds: 90,
  },
  {
    id: "p3-cities",
    part: 3,
    topic: "Cities",
    prompt: "What can cities do to create more quiet public spaces?",
    prepSeconds: 10,
    answerSeconds: 90,
  },
  {
    id: "p3-communication",
    part: 3,
    topic: "Communication",
    prompt: "Do people have fewer meaningful conversations than in the past?",
    prepSeconds: 10,
    answerSeconds: 90,
  },
  {
    id: "p3-work",
    part: 3,
    topic: "Work",
    prompt: "Why do some people find it difficult to separate work from personal life?",
    prepSeconds: 10,
    answerSeconds: 90,
  },
  {
    id: "p3-traditions",
    part: 3,
    topic: "Traditions",
    prompt: "How should communities keep local traditions relevant to young people?",
    prepSeconds: 10,
    answerSeconds: 90,
  },
  {
    id: "p3-consumption",
    part: 3,
    topic: "Consumption",
    prompt: "What influences people to replace products that still work?",
    prepSeconds: 10,
    answerSeconds: 90,
  },
  {
    id: "p3-public-space",
    part: 3,
    topic: "Public spaces",
    prompt: "What makes a public place welcoming to different age groups?",
    prepSeconds: 10,
    answerSeconds: 90,
  },
];

export const partTips: Record<1 | 2 | 3, string[]> = {
  1: ["先直接回答，再补充一个个人细节", "控制在 2–4 句话", "避免只回答 Yes 或 No"],
  2: ["按要点组织，而不是逐条机械回答", "加入时间、地点和感受", "准备时只记关键词"],
  3: ["先表达观点，再解释原因", "比较不同情况或人群", "用一个例子支持抽象观点"],
};

export function getDailyQuestion() {
  const dayIndex = Math.floor(Date.now() / 86_400_000);
  return questions[dayIndex % questions.length];
}
